import type { Metadata } from 'next';

import ClientProvider from '@/component/clientProvider/ClientProvider';
import Header from '@/component/layout/header/HeaderContainer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <ClientProvider>
        <body>
          <Header />
          {children}
        </body>
      </ClientProvider>
    </html>
  );
}
