import type { Metadata } from 'next';

import Header from '@/component/layout/header/HeaderContainer';
import StylesProvider from '@/styles/provider/StyleProvider';
import ReactClientProvider from '@/query/clientQueryProvider/ClientQueryProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <StylesProvider>
        <ReactClientProvider>
          <body>
            <Header />
            {children}
          </body>
        </ReactClientProvider>
      </StylesProvider>
    </html>
  );
}
